[project]
name = "base_robyn"
version = "0.1.0"
description = "A base Robyn project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robyn"
]
[dependency-groups]
dev = [
    "pytest",
    "pytest-html"
]